<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $form->title }} - Submissions Report</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            font-size: 12px;
            margin: 0;
            padding: 10px;
        }
        h2 {
            font-size: 20px;
            color: #1a202c;
            margin-bottom: 5px;
        }
        .meta {
            margin-bottom: 20px;
            color: #4a5568;
            font-size: 11px;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 10px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            border: 1px solid #cbd5e0;
            padding: 8px 6px;
            text-align: left;
        }
        th {
            background-color: #f7fafc;
            color: #4a5568;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f8fafc;
        }
        .footer {
            margin-top: 30px;
            font-size: 10px;
            color: #718096;
            text-align: center;
        }
    </style>
</head>
<body>

    <h2>{{ $form->title }}</h2>
    <div class="meta">
        Type: {{ ucfirst($form->type) }} | 
        Total Views: {{ $form->views }} | 
        Total Submissions: {{ $form->submissions->count() }} | 
        Conversion Rate: {{ $form->conversion_rate }}% | 
        Exported: {{ now()->format('Y-m-d H:i:s') }}
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Submitted At</th>
                <th>Submitted By</th>
                @foreach ($form->fields as $field)
                    <th>{{ $field->label }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($form->submissions as $submission)
                <tr>
                    <td>#{{ $submission->id }}</td>
                    <td>{{ $submission->created_at->format('Y-m-d H:i') }}</td>
                    <td>{{ $submission->user ? $submission->user->name : 'Guest' }}</td>
                    @foreach ($form->fields as $field)
                        <td>
                            @php
                                $val = $submission->data[$field->id] ?? '-';
                            @endphp
                            @if (is_array($val))
                                {{ implode(', ', $val) }}
                            @else
                                {{ $val }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Form Builder System
    </div>

</body>
</html>
