<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Submission #{{ $submission->id }} - {{ $form->title }}</title>
    <style>
        body {
            font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
            color: #333;
            font-size: 13px;
            margin: 0;
            padding: 20px;
        }
        .header {
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 15px;
            margin-bottom: 25px;
        }
        h2 {
            font-size: 22px;
            color: #1a202c;
            margin: 0 0 5px 0;
        }
        .meta {
            color: #4a5568;
            font-size: 11px;
        }
        .submission-card {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 20px;
            background-color: #f8fafc;
        }
        .field-group {
            margin-bottom: 15px;
            border-bottom: 1px solid #edf2f7;
            padding-bottom: 12px;
        }
        .field-group:last-child {
            border-bottom: none;
            padding-bottom: 0;
            margin-bottom: 0;
        }
        .field-label {
            font-weight: bold;
            color: #4a5568;
            margin-bottom: 4px;
            font-size: 11px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        .field-value {
            font-size: 14px;
            color: #1a202c;
            line-height: 1.4;
        }
        .footer {
            margin-top: 40px;
            font-size: 10px;
            color: #a0aec0;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="header">
        <h2>{{ $form->title }}</h2>
        <div class="meta">
            Submission: <strong>#{{ $submission->id }}</strong> | 
            Submitted At: <strong>{{ $submission->created_at->format('Y-m-d H:i:s') }}</strong> | 
            Submitted By: <strong>{{ $submission->user ? $submission->user->name : 'Guest' }}</strong>
        </div>
    </div>

    <div class="submission-card">
        @foreach ($form->fields as $field)
            <div class="field-group">
                <div class="field-label">{{ $field->label }}</div>
                <div class="field-value">
                    @php
                        $val = $submission->data[$field->id] ?? '-';
                    @endphp
                    @if (is_array($val))
                        {{ implode(', ', $val) }}
                    @else
                        {!! nl2br(e($val)) !!}
                    @endif
                </div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by Form Builder System
    </div>

</body>
</html>
